"""Add SleepSession table

Revision ID: 153f9eda6869
Revises: 84cf9d7aed41
Create Date: 2025-07-02 00:41:49.605428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153f9eda6869'
down_revision: Union[str, None] = '84cf9d7aed41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_sessions_id'), 'sleep_sessions', ['id'], unique=False)
    op.add_column('healthdata', sa.Column('metric_type', sa.String(), nullable=True))
    op.add_column('healthdata', sa.Column('value', sa.Float(), nullable=True))
    op.add_column('healthdata', sa.Column('systolic', sa.Integer(), nullable=True))
    op.add_column('healthdata', sa.Column('diastolic', sa.Integer(), nullable=True))
    op.drop_column('healthdata', 'spo2')
    op.drop_column('healthdata', 'blood_pressure')
    op.drop_column('healthdata', 'heart_rate')
    op.add_column('users', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'google_refresh_token')
    op.drop_column('users', 'google_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_access_token', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token', sa.VARCHAR(), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token')
    op.add_column('healthdata', sa.Column('heart_rate', sa.FLOAT(), nullable=True))
    op.add_column('healthdata', sa.Column('blood_pressure', sa.VARCHAR(), nullable=True))
    op.add_column('healthdata', sa.Column('spo2', sa.FLOAT(), nullable=True))
    op.drop_column('healthdata', 'diastolic')
    op.drop_column('healthdata', 'systolic')
    op.drop_column('healthdata', 'value')
    op.drop_column('healthdata', 'metric_type')
    op.drop_index(op.f('ix_sleep_sessions_id'), table_name='sleep_sessions')
    op.drop_table('sleep_sessions')
    # ### end Alembic commands ###
